/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mhrs;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class SearchGUI extends javax.swing.JFrame {

    private static final int idSize = 8;

    /**
     * Creates new form GUI
     */
    public SearchGUI() {
        initComponents();
        this.setTitle("Medical History Report System - Search");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2); //centers frame on screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientLastName = new javax.swing.JTextField();
        patientFirstName = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        patientID = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientLastNameKeyTyped(evt);
            }
        });

        patientFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientFirstNameKeyTyped(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        patientID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000000"))));
        patientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientIDKeyTyped(evt);
            }
        });

        jLabel1.setText("Patient ID");

        jLabel2.setText("Last Name");

        jLabel3.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientID)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 315, Short.MAX_VALUE)
                        .addComponent(searchButton))
                    .addComponent(patientLastName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        MHPage searchResult = null;
        if (patientID.isEnabled()) {
            MHPage p = null;
            try {
                p = new MHPage(0, "John", "Smith");
                ArrayList<Condition> cond = new ArrayList<>();
                ArrayList<Procedure> proc = new ArrayList<>();
                ArrayList<FamilyMember> fam = new ArrayList<>();

                //uncomment below for some example objects, or fill in the blank form manually
                cond.add(new Condition("Tinnitus", "keep away from loud noises"));
                cond.add(new Condition("Depression", "keep away from memes"));
                cond.add(new Condition("Heat Vision", "keep sunglasses on at all times"));

                proc.add(new Procedure("Vasectomy", Date.from(Instant.now()), "went smoothly"));
                proc.add(new Procedure("Heart Surgery", Date.from(Instant.EPOCH), "just barely survived"));

                ArrayList<Condition> cond1 = new ArrayList<>();
                cond1.add(new Condition("Testicular Cancer", "o no"));
                cond1.add(new Condition("Rabies", "from kissing his dog"));

                ArrayList<Condition> cond2 = new ArrayList<>();
                cond2.add(new Condition("Stanky Leg", "ooh watch me, watch me\n now watch me whip\n now watch me nay-nay"));
                fam.add(new FamilyMember("Father", cond1));
                fam.add(new FamilyMember("Son", cond2));

                p.setConditions(cond);
                p.setProcedures(proc);
                p.setFamily(fam);
            } catch (Exception ex) {
                Logger.getLogger(MHRS.class.getName()).log(Level.SEVERE, null, ex);
                System.exit(1);
            }
            PageViewGUI.main(p);
            this.setVisible(false);
        } else if (!patientID.isEnabled()) {
            //Search Database with first and last name (Do we need to require both?)
        } else if (patientID.getText().equals("") && patientLastName.getText().equals("") && patientFirstName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No text entered", "Blank Search Values", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "ID/First/Last name not found in database", "Patient Not Found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void patientLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientLastNameKeyTyped
        String first = patientFirstName.getText();
        String last = patientLastName.getText();
        int i = evt.getExtendedKeyCode();
        char c = evt.getKeyChar();

        if (last.equals("") && i != 8 && isAlpha(c)) {
            patientID.setEnabled(false);
        }
        if (last.length() == 0 && i == 8 && first.equals("")) {
            patientID.setEnabled(true);
        }
        if (!isAlpha(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_patientLastNameKeyTyped

    private void patientIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientIDKeyTyped
        String text = patientID.getText();
        int i = evt.getExtendedKeyCode();
        char c = evt.getKeyChar();

        if (text.equals("") && i != 8 && isNum(c)) {
            patientFirstName.setEnabled(false);
            patientLastName.setEnabled(false);
        }
        if (isSize(text) || !isNum(c)) {
            evt.consume();
        }
        if (text.length() == 0 && i == 8) {
            patientFirstName.setEnabled(true);
            patientLastName.setEnabled(true);
        }
    }//GEN-LAST:event_patientIDKeyTyped

    private void patientFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientFirstNameKeyTyped
        String first = patientFirstName.getText();
        String last = patientLastName.getText();
        int i = evt.getExtendedKeyCode();
        char c = evt.getKeyChar();

        if (first.equals("") && i != 8 && isAlpha(c)) {
            patientID.setEnabled(false);
        }
        if (first.length() == 0 && i == 8 && last.equals("")) {
            patientID.setEnabled(true);
        }
        if (!isAlpha(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_patientFirstNameKeyTyped

    private boolean isAlpha(char c) {
        return "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM".indexOf(c) != -1;
    }

    private boolean isSize(String s) {
        return (s.length() + 1) > idSize;
    }

    private boolean isNum(char c) {
        return "1234567890".indexOf(c) != -1;
    }

    private MHPage spawnGhostPage() {
        MHPage test = new MHPage(0000000, "John", "Smith");

        return test;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField patientFirstName;
    private javax.swing.JFormattedTextField patientID;
    private javax.swing.JTextField patientLastName;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
